[project]
name = "emuru"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Galaxerr", email = "160768649+Galaxerr@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
]

[project.scripts]
emuru-index = "emuru.cli:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
